

@HOSTAPI=http://localhost:3333

###
# @name TOKEN_REST
POST {{HOSTAPI}}/session HTTP/1.1
Content-Type: application/json
x-tenantCode: 000000001
x-tenantManageCode: 000000001

{
"email": "admin@admin.com.br",
"password": "123"
}

//-----------------------------------------------------------------------------------------------

###
POST {{HOSTAPI}}/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "table": 114
}

###
POST {{HOSTAPI}}/order/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "order_id": "4d7a3e2b-f759-4f78-9ea2-ac65f703aaef",
    "product_id": "ef2abe4e-8a69-4476-ae42-27316ba0d6a1",
    "amount": 1
}

###
PUT  {{HOSTAPI}}/order/send HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "order_id": "982713c3-c261-40e0-bf3d-26e25bf9218c"
}

###
GET   {{HOSTAPI}}/orders HTTP/1.1
Content-Type: application/body
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

###
DELETE  HTTP/1.1 {{HOSTAPI}}/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "order_id": "782b4db8-3b3c-43e8-8b23-bbdfb0f46d14"
}