

@HOSTAPI=http://localhost:3333

###
# @name TOKEN_REST
POST {{HOSTAPI}}/session HTTP/1.1
Content-Type: application/json
x-tenantCode: 000000001
x-tenantManageCode: 000000001

{
"email": "admin@admin.com.br",
"password": "123"
}

//-----------------------------------------------------------------------------------------------

###
POST {{HOSTAPI}}/order HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "table": 112
}

###
POST {{HOSTAPI}}/order/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "order_id": "c8fd3bdc-588e-4cee-80a5-fa92a0628cc8",
    "product_id": "ef2abe4e-8a69-4476-ae42-27316ba0d6a1",
    "amount": 1
}

###
PUT  {{HOSTAPI}}/order/send HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}

{
    "order_id": "b448021a-3939-4683-bbbd-4d37d7aae7f1"
}

###
GET   {{HOSTAPI}}/orders HTTP/1.1
Content-Type: application/body
Authorization: Bearer {{TOKEN_REST.response.body.$.token}}